config/routes.rb
Rails.application.routes.draw do
  resources :tier_lists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tier_list.rb
class TierList < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tier_lists_controller.rb
class TierListsController < ApplicationController
  before_action :set_tier_list, only: %i[ show edit update destroy ]

  # GET /tier_lists or /tier_lists.json
  def index
    @tier_lists = TierList.all
  end

  # GET /tier_lists/1 or /tier_lists/1.json
  def show
  end

  # GET /tier_lists/new
  def new
    @tier_list = TierList.new
  end

  # GET /tier_lists/1/edit
  def edit
  end

  # POST /tier_lists or /tier_lists.json
  def create
    @tier_list = TierList.new(tier_list_params)

    respond_to do |format|
      if @tier_list.save
        format.html { redirect_to tier_list_url(@tier_list), notice: "Tier list was successfully created." }
        format.json { render :show, status: :created, location: @tier_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tier_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tier_lists/1 or /tier_lists/1.json
  def update
    respond_to do |format|
      if @tier_list.update(tier_list_params)
        format.html { redirect_to tier_list_url(@tier_list), notice: "Tier list was successfully updated." }
        format.json { render :show, status: :ok, location: @tier_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tier_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tier_lists/1 or /tier_lists/1.json
  def destroy
    @tier_list.destroy!

    respond_to do |format|
      format.html { redirect_to tier_lists_url, notice: "Tier list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tier_list
      @tier_list = TierList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tier_list_params
      params.fetch(:tier_list, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tier_lists_helper.rb
module TierListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TierListApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tier_lists/_form.html.erb
<%= form_with(model: tier_list) do |form| %>
  <% if tier_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tier_list.errors.count, "error") %> prohibited this tier_list from being saved:</h2>

      <ul>
        <% tier_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tier_lists/_tier_list.html.erb
<div id="<%= dom_id tier_list %>">
</div>

app/views/tier_lists/edit.html.erb
<h1>Editing tier list</h1>

<%= render "form", tier_list: @tier_list %>

<br>

<div>
  <%= link_to "Show this tier list", @tier_list %> |
  <%= link_to "Back to tier lists", tier_lists_path %>
</div>

app/views/tier_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tier lists</h1>

<div id="tier_lists">
  <% @tier_lists.each do |tier_list| %>
    <%= render tier_list %>
    <p>
      <%= link_to "Show this tier list", tier_list %>
    </p>
  <% end %>
</div>

<%= link_to "New tier list", new_tier_list_path %>

app/views/tier_lists/new.html.erb
<h1>New tier list</h1>

<%= render "form", tier_list: @tier_list %>

<br>

<div>
  <%= link_to "Back to tier lists", tier_lists_path %>
</div>

app/views/tier_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tier_list %>

<div>
  <%= link_to "Edit this tier list", edit_tier_list_path(@tier_list) %> |
  <%= link_to "Back to tier lists", tier_lists_path %>

  <%= button_to "Destroy this tier list", @tier_list, method: :delete %>
</div>